---
- hosts: kube
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - include_tasks: tasks/vagrant-setup.yml

  roles:
    - fail2ban
    - ssh
    - autoupdate
    - swap
    - docker
    - kubernetes
