---
- name: dependencies.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add apt key.
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: add_repository_key
  ignore_errors: "{{ kubernetes_apt_ignore_key_error }}"

- name: Add repository.
  apt_repository:
    repo: "{{ kubernetes_apt_repository }}"
    state: present
    update_cache: true

- name: Add apt template.
  template:
    src: template.j2
    dest: /etc/apt/preferences.d/kubernetes
    mode: 0644
